name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ^0.10.0
  supabase_flutter: ^1.10.0 
  camera: ^0.11.1
  path_provider: ^2.1.1
  path: ^1.8.3
  geolocator: ^10.0.0
  image_picker: ^1.1.2
  fluttertoast: ^8.0.9
  firebase_core: ^3.12.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.0+1
  timeago: ^3.2.2
  geocoding: ^3.0.0
  url_launcher: ^6.1.7
  image: ^4.5.4
  flutter_local_notifications: ^17.2.1
  awesome_notifications: ^0.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animal_recognition.tflite