name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  camera: ^0.10.0+1
  path_provider: ^2.1.1
  path: ^1.8.3
  geolocator: ^10.0.0
  image_picker: ^0.8.7+3
  fluttertoast: ^8.0.9
  firebase_core: ^3.12.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  permission_handler: ^10.4.0
  flutter_local_notifications: ^14.0.0
  timeago: ^3.2.2
  geocoding: ^2.1.1
  url_launcher: ^6.1.7
  tflite_flutter: ^0.11.0
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt

